- client/.storybook/main.js
- client/src/components/BottomNavigationBar/index.tsx
- client/src/components/BottomNavigationButton/index.tsx
- client/src/components/BottomNavigationButton/style.ts
1. storybook에서 사용하는 & 사용할 것으로 예상되는 경로를 위한 Path alias 모두 설정해뒀습니다.
2. 네비게이션바의 버튼을 별도의 컴포넌트로 분리하였습니다.
3. 기존에 페이지를 이동하고 뒤로가기 버튼을 누르면, 이전의 화면으로 가졌으나,
history replace처리를 통해 depth가 0이라면 나가지게 설정해뒀습니다.
```
const BottomNavigationButton = ({ path, iconImageUrl, title }: BottomNavigationButtonProps) => {
return (
<s.LinkButton
to={path}
className={({ isActive }) => (isActive ? "active" : "inactive")}
replace
>
</s.LinkButton>
);
};
```
`<BottomNavigationButton path="/" iconImageUrl={homeIcon} title="홈 화면 이동 아이콘" />`
```
config.resolve.alias["@pages"] = path.resolve(__dirname, "../src/pages");
config.resolve.alias["@hooks"] = path.resolve(__dirname, "../src/hooks");
config.resolve.alias["@canvas"] = path.resolve(__dirname, "../src/canvas");
config.resolve.alias["@styles"] = path.resolve(__dirname, …
```
> [FE] 코어 - 공통 레이아웃 - 하단 네비게이션바 기능 추가 & 리팩토링

- server/src/app.module.ts
- server/src/main.ts
- server/src/oauth/google-oauth/dto/create-google-oauth.dto.ts
- server/src/oauth/google-oauth/dto/update-google-oauth.dto.ts
- server/src/oauth/google-oauth/google-oauth.controller.spec.ts
- server/src/oauth/google-oauth/google-oauth.controller.ts
- server/src/oauth/google-oauth/google-oauth.module.ts
- server/src/oauth/google-oauth/google-oauth.service.spec.ts
- server/src/oauth/google-oauth/google-oauth.service.ts
- server/src/oauth/google-oauth/utils/google.guards.ts
- server/src/oauth/google-oauth/utils/google.serializer.ts
- server/src/oauth/google-oauth/utils/google.strategy.ts
- server/src/typeorm/entities/User.ts
- server/src/types/request.type.ts
- server/src/types/user.type.ts
[Class constructor MixinStrategy cannot be invoked without 'new'](https://github.com/nestjs/nest/issues/2190)
[OAuth 2.0 Playground "Something bad happened: 500 HTTP error"](https://stackoverflow.com/questions/61250537/oauth-2-0-playground-something-bad-happened-500-http-error)
[Typescript Error: Property 'user' does not exist on type 'Request'](https://stackoverflow.com/questions/44383387/typescript-error-property-user-does-not-exist-on-type-request)
[Nest can't resolve dependencies of the Service (?). Please make sure that the argument Repository at index [0] is available in the ResultIoModule](https://junior-datalist.tistory.com/147)
> Google Login API 구현
> Google Login 정보 DB에 저장
> [How to Implement Login with Google in Nest JS](https://dev.to/imichaelowolabi/how-to-implement-login-with …
> [BE] API 구현 - Google Login API 구현, Google Login 정보 DB에 저장

- server/src/alarms/alarms.controller.ts
- server/src/alarms/alarms.service.ts
- server/src/alarms/entities/alram.entity.ts
- server/src/users/entities/user.entity.ts
기존 테이블 관계로 COUNT를 실행했지만, JOIN 이슈로 인해 데이터 1,000개 받아오는데에 30초 정도 걸림
생각해보니 alarm 테이블에서의 외래키의 필요성을 느끼지 못해 관계를 끊음
> 사용자의 Id를 요청하면 해당 사용자가 읽지 않은 alarm의 수를 응답하는 API
> JOIN의 심각한 성능 저하로 인해 FK 관계 제거함
[typeORM에서 COUNT 쓰기](https://github.com/typeorm/typeorm/issues/673)
> [BE] API 구현 - Alarm API 구현 (공통) - Fetch Unread Alram API 구현 

- client/src/components/ProfileImageContainer/index.tsx
- client/src/components/ProfileImageContainer/style.ts
- client/src/stories/BottomNavigationBar.stories.tsx
- client/src/stories/Calendar.stories.tsx
#52
- 프로필의 크기 조절이 안되던 문제를 해결하였습니다.
- 컨테이너를 감싸는 부모 div의 크기에 따라 변경됩니다.
[css 이미지 겹치기](https://bebeya.tistory.com/entry/css-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EA%B2%B9%EC%B9%98%EA%B8%B0-2%EA%B0%9C-3%EA%B0%9C-position-absolute-relative)
> [FE] 홈 페이지 - 메인 - 프로필 이미지 컨테이너 리팩토링

- server/src/config/typeorm.config.ts
- server/src/exercises/dto/every-date.dto.ts
- server/src/exercises/exercises.service.ts
- server/src/sbd_records/sbd_records.service.ts
외래키 관계 제약이 걸린 컬럼을 가져올 때 내부적으로 JOIN을 날려서 성능 이슈가 있었다.
TypeORM의 강점 중 하나인 queryBuilder 문법을 쓰면, 기존의 매서딩 방식에 비해 raw한 방식이지만 속도 향상을 기대할 수 있고,
쿼리 튜닝이 용이해서 JOIN을 쓰지 않고서도 외래키 관계 제약이 걸린 컬럼을 그냥 가져올 수 있는 큰 이점이 있다.
Service 단의 모든 문법을 query builder 문법으로 수정
[TypeORM - Query Builder 공식 문서](https://typeorm.io/select-query-builder#)
> [BE] API 구현 - 모든 API를 TypeORM - query builder 문법으로 수정

- server/src/alarms/alarms.service.ts
- server/src/alarms/entities/alram.entity.ts
- server/src/config/typeorm.config.ts
- server/src/exercises/entities/exercise.entity.ts
- server/src/routines/entities/routine.entity.ts
- server/src/sbd_records/entities/sbd_record.entity.ts
- server/src/users/entities/user.entity.ts
- server/src/users/users.controller.ts
ERD 설계도와 DB간의 동기화 및 최신화가 되지 않아
서로 컬럼 명과 그 의미를 까먹는 문제가 발생
하여 이를 최신화하기 위해 회의를 거친 결과 다음와 같은 PR을 작성하게 되었음
다만 아래 사진을 보면 user 테이블의 컬럼들은 nullable 설정이 되어있는데,
이는 현재 Google OAuth 로그인과 회원 정보 기입의 실행 시점이 다르기 때문에
일시적으로 다음과 같이 설정해 놓았음
> [BE] ERD 최종본 바탕으로 Entity 수정

- client/src/App.tsx
- client/src/components/SearchResultUserProfile/index.tsx
- client/src/components/SearchResultUserProfile/style.ts
- client/src/pages/SearchPage/index.tsx
- client/src/pages/SearchPage/styles.ts
#128 
사용자 이름을 입력하면 디바운싱을 하여, 입력이 끝나는 시점의 키워드를 받고 유저를 검색합니다.
1. 유저 리스트를 맨 처음 화면 랜더링시 받아옵니다.
2. 검색 시, 받아온 유저 리스트를 기반으로 탐색합니다.
* 모든 자기소개가 존재하지 않고 프로필이미지가 동일 한 것은 현재 사용하는 정보가 user.name뿐이기 때문입니다.
* 현재 백엔드에서는 id, name, introduce, img에 대한 정보가 필요합니다.
* 그러나 현재의 userlist는 name만 반환하여 map의 고유한 key값을 설정하지 못했고 이러한 이유로 영상에서 오류가 발생할 수 있습니다.
* userList로 넘겨주는 형태에 대해서 고려해봐야할 것 같습니다.
https://user-images.githubusercontent.com/78866590/203785714-28574120-19c2-4b35-9a78-8abf95016e54.mov
- https://www.youtube.com/watch?v=By49qqkzmzA
- https://blog.hubspot.com/website/css-transition-vs-animation
- https://minoo.medium.com/%EB%B2%88%EC%97%AD-5%EA%B0%80%EC%A7%80-%EB%A6%AC%EC%95%A1%ED%8A%B8-%EC%95%A0%EB%8B%88%EB%A9%94%EC%9D%B4%EC%85%98-%EC%9E%A5-%EB%8B%A8%EC%A0%90-%EB%B9%84%EA%B5%90-react-animations-in-depth-884ff6e6 …
> [FE] 검색 페이지 - 메인 - 검색기능 및 사용자 추천 자동완성 기능

- client/src/pages/SearchPage/index.tsx
- server/src/main.ts
- 배포 서버에서 api 서버 접속이 CORS 오류 발생
- search page의 axios에 `withCredentials: true` 설정 추가
- server의 main.ts `origin: ["https://www.fitory.ga", "https://fitory.ga"]`, `credentials: true` 설정 추가
- nginx에서 localhost:8080번의 proxy_pass 추가
[[ERROR] The 'Access-Control-Allow-Origin' header contains multiple values](https://minholee93.tistory.com/entry/ERROR-The-Access-Control-Allow-Origin-header-contains-multiple-values)
[[WEB] 📚 악명 높은 CORS 개념 & 해결법 - 정리 끝판왕 👏](https://inpa.tistory.com/entry/WEB-%F0%9F%93%9A-CORS-%F0%9F%92%AF-%EC%A0%95%EB%A6%AC-%ED%95%B4%EA%B2%B0-%EB%B0%A9%EB%B2%95-%F0%9F%91%8F)
[[Nginx] CORS 설정](https://greeng00se.tistory.com/119)
[CORS 정복기](https://velog.io/@prayme/CORS-%EC%A0%95%EB%B3%B5%EA%B8%B0)
> 서버 배포 1차 - CORS 오류 해결

- server/package-lock.json
- server/package.json
- server/src/domain/oauth/google-oauth/dto/access-token.dto.ts
- server/src/domain/oauth/google-oauth/google-oauth.controller.ts
- server/src/domain/oauth/google-oauth/google-oauth.module.ts
- server/src/domain/oauth/google-oauth/google-oauth.service.ts
- server/src/domain/oauth/google-oauth/utils/google.strategy.ts
- 기존에는 프론트측과의 통신을 고려하지 않은 채 구현이 되어있었다.
- 프론트측과 얘기를 나눠 API에 대한 협의를 했다.
- 이를 토대로 API를 재구성한다.
- ❗️현재 프론트랑 같이 디버깅을 해보지 않아서 문제 발생시 바로 알려주세요.
- 신규 유저일 경우 jwt 토근과 함께 `statusCode : 200, validate: true` 를 보냅니다.
- 이미 회원가입한 유저일 경우 `statusCode : 200, validate: false` 를 보냅니다.
- ❗️`동규님` 아니면 404같은 에러코드로 보내드릴까요?
> 작업한 사진을 첨부할 경우 여기에 추가하세요.
> [BE] API 구현 - AUTH API - Google OAuth 프론트와의 연동성 수정

- server/src/domain/exercises/dto/exercise.dto.ts
- server/src/domain/exercises/exercises.service.ts
- server/src/domain/routines/converter/routines.converter.ts
- server/src/domain/routines/dto/single-routine.dto.ts
- server/src/domain/routines/routines.controller.ts
- server/src/domain/routines/routines.service.ts
- server/src/exception/exceptions.ts
- server/src/types/domain.d.ts
- POST 형식
```
{
"userId": 1,
"routineName": "테스트 루틴",
"exerciseList": [
{
"exerciseName": "테스트 운동",
"setList": [
{
"kg": 100,
"count": 5
}
]
},
{
"exerciseName": "테스트 운동2",
"setList": [
{
"kg": 200,
"count": 10
}
]
}
]
}
```
- Response
```
{
"ok": true,
"statusCode": 200,
"response": "Routine save success"
}
```
- 클라이언트에서 온 루틴 정보를 파싱해서 DB에 저장한다.
> [BE] API 구현 - ROUTINE API - Save Routine API

- server/src/domain/exercises/dto/exercise.dto.ts
- server/src/domain/exercises/exercises.service.ts
- server/src/domain/mock/mock.service.ts
- server/src/domain/sbd_records/converter/sbd_records.converter.ts
- server/src/domain/sbd_records/entities/sbd_record.entity.ts
- server/src/domain/sbd_records/sbd_records.service.ts
- server/src/domain/users/entities/user.entity.ts
- server/src/types/domain.d.ts
클라이언트 측에서는 시간 조작의 위험성이 있어 이를 서버 시간 기준으로 전부 조정함
dayjs 객체를 사용해 서버 시간 기준으로 수정함
또한 날짜순 정렬 메서드도 timestamp 기준으로 정렬하게끔 수정함
> [BE] date를 서버 시간으로 조정

- server/src/domain/alarms/alarms.service.ts
- server/src/domain/follows/follows.service.ts
- server/src/domain/users/users.service.ts
#284 
사용자가 Alarm 페이지 접속 시 요청하는 API에
알림 읽음 표시 로직을 붙여서 작동하도록 수정
또한 알림 페이지에서는
`안읽은 알림` + `읽었지만 아직 1달이 지나지 않은 알림`
이렇게 랜더링되도록 필터링 구현
> [BE] API - Alarm 읽음 처리 구현

- server/src/domain/users/users.controller.ts
- 회원가입 시(user id가 없는 상태) 유저 이름 중복 검사 API를 실행 시 Guard에 막히는 버그 수정
- 닉네임 중복 검사 시 Guard 검증 예외 처리 추가
> [BE] API 구현 - AUTH API - Guard 예외 처리

- server/src/app.module.ts
- server/src/exception/exceptions.ts
- server/src/guard/jwt.guard.ts
- server/src/guard/jwt.strategy.ts
- server/src/main.ts
- AuthGuard에서 access_token의 userId를 못불러오던 버그
- 알아본 결과 AuthGuard에서 비동기 관련 문제로 access token의 userId를 못불러오던 버그가 발생했다.
- 그래서 `getReuest`를 하기 전에 `const guardResult = await super.canActivate(context);`를 통해 AuthGuard를 먼저 불러 request안에 user를 inject하도록 했다.
[PassportJS, NestJS: canActivate method of AuthGuard('jwt')](https://stackoverflow.com/questions/65557077/passportjs-nestjs-canactivate-method-of-authguardjwt)
> [BE] API 구현 - AUTH API - AuthGuard 버그 수정

- client/src/pages/JoinPage/index.tsx
- client/src/pages/PageTemplate.tsx
> 실수로 회원가입 페이지에서도 로컬 스토리지의 user id를 확인하고 없으면 로그인 페이지로 이동하게 했다..
- 회원가입 페이시에서는 로컬 스토리지의 user id 확인 절차를 거치지 않도록 처리
>회원가입 페이시에서는 로컬 스토리지의 user id 확인 절차를 거치지 않도록 처리
> [FE] 회원가입 페이지 - 예외처리

- client/src/api/UserAPI.ts
- server/src/domain/alarms/alarms.controller.ts
- server/src/domain/alarms/alarms.service.ts
#268 
알람 페이지에서 무한 스크롤 요청시 index(pk)를 같이 보내 10개씩 끊어서 응답이 가도록 구현함
1번 사용자가 받은 알림은 총 5개
실험의 편의를 위해 2개씩 끊어서 캡쳐했습니다
아래와 같이 인덱스 같이 보내면 응답이 옵니다
(check는 잠시 무시)
> [BE] API - 무한 스크롤 위해 10개씩 응답

- client/src/App.tsx
- client/src/api/ChallengeAPI.ts
- client/src/hooks/query/useAllExerciseDate.ts
- client/src/hooks/query/useBestChallengeScore.ts
- client/src/hooks/query/useExerciseProfile.ts
- client/src/hooks/query/useRecentChallengeTime.ts
- client/src/hooks/query/useRoutineList.ts
- client/src/hooks/query/useUserInfo.ts
페이지를 이동하거나, 탭을 잠시 닫았다가 다시 열 때마다 캐싱이 적용되지 않았다.
- 아래 코드와 같이 QueryClient의 defaultOptions을 적용하여 해결했다.
```ts
const queryClient = new QueryClient({
defaultOptions: {
queries: {
suspense: true,
refetchOnWindowFocus: false,
refetchOnMount: false,
retry: false,
},
},
});
```
- QueryClient default 캐싱 설정 적용
- 캐싱되면 안되는 useQuery에 캐싱 해제 옵션 추가
- QueryClient default Suspense 설정 적용
> 페이지를 이동할 때마다 캐싱이 되지 않고 서버에 API를 호출하는데, 이를 해결한다.
> [[[react query] stale이란? (feat, 캐싱,use query,fetch, react query에 대해 알아보기)](https://2ham-s.tistory.com/407)](https://2ham-s.tistory.com/407)
> [FE] 코어 - React Query 캐싱 문제 해결

- client/src/pages/HomePage/index.tsx
- server/src/app.module.ts
- server/src/domain/event/event.controller.ts
- server/src/domain/event/event.module.ts
- server/src/domain/event/event.service.ts
- server/src/domain/exercises/exercises.controller.ts
- server/src/domain/exercises/exercises.module.ts
- server/src/domain/follows/follows.controller.ts
- server/src/domain/follows/follows.module.ts
- server/src/domain/follows/follows.service.ts
- server/src/guard/jwt.guard.ts
#328 
각 사용자는 초기 접속 시 각 userId로 된 채널을 EventEmitter에 등록함
누군가 운동을 완료하거나 팔로우하면 연관 관계가 있는 사용자에게 SSE 발신하여
클라이언트에서 알림 갱신 신호를 받아 Get Unread Alarm API를 호출하여
실시간으로 알림을 갱신하도록 구현함
[SSE core](https://stackoverflow.com/questions/67202527/can-we-use-server-sent-events-in-nestjs-without-using-interval)
[NestJS DI](https://medium.com/crocusenergy/nestjs-modules-%EA%B0%9C%EB%85%90-%EB%B0%8F-%EC%8B%A4%EC%8A%B5-758b1328e9e7)
> [BE] API - Alarm - SSE로 읽지 않은 알람 전송

- server/package.json
- server/src/main.ts
- AuthGuard로 인해 개발(디버깅)에 지속적으로 지장이 생겨 가드를 사용하지 않고 실행 가능한 스크립트 추가
- `npm run start:noguard` 를 통해 가드 비활성화한채로 실행 가능 이외에는 `start:dev`와 동일
> [BE] No AuthGuard 스크립트 추가

- server/src/domain/users/users.controller.ts
- server/src/domain/users/users.service.ts
Get User Info API에서 follower, following 정보를 가져오기 위해 follow 테이블에 2번이나 접근해야했음
Do Follow, Cancel Follow API 요청시 TRIGGER를 발동시켜, 
자동으로 user 테이블에 follower_count, following_count 컬럼이 UPDATE 되도록 변경함
TRIGGER 설정으로 인해 이를 대체
성능 향상 기대
트리거 파일
> [BE] DB - Trigger 적용으로 인해 Get User Info API에 팔로워 가져오기 삭제

- client/webpack.config.js
> 배포 환경에서의favicon.ico 파일의 403 에러를 해결한다.
> [FE] favicon 403 에러 해결

- client/public/pwaServiceWorker.js
favicon 403 forbbiden로 인한 서비스 워커 에러가 발생한 것으로 파악했다.
> 배포 환경에서의 서비스 워커의 프로미스 에러를 해결한다.
> [FE] 서비스 워커 에러 해결
