server/.eslintignore, server/.eslintrc.json, server/package-lock.json, server/package.json, server/tsconfig.json
> 프로젝트에 사용되지 않는 파일 또는 옵션은 제거하고, 필요하다 판단되는 부분을 추가했습니다.
> [[TS] 📘 타입스크립트 컴파일 설정 - tsconfig 옵션 정리](https://inpa.tistory.com/entry/TS-%F0%9F%93%98-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-tsconfigjson-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0-%EC%B4%9D%EC%A0%95%EB%A6%AC)
=> [BE] 코어 - 개발 환경 수정

client/src/styles/Theme.ts
=> [FE] 코어 - 스타일 설정 - styled components의 theme 설정

server/.eslintrc.json
> 프론트와의 일관성을 위해 eslint.js -> eslint.json 수정
=> [BE] - 코어 - 개발 환경 설정 - eslint 수정

client/.storybook/preview.js
어제 생성해둔 테마와 글로벌 스타일을 스토리북에 반영하였습니다.
=> [FE] 코어 - 개발 환경 설정 - storybook, 개발 환경에 맞는 스토리북 세팅 변경

client/.storybook/main.js, client/tsconfig.json
feature 개발에 필요한 path alias 설정을 완료했습니다.
path alias를 사용함에 따라 스토리북 설정에 변경이 필요했고 이를 적용했습니다.
=> [FE] 코어 - 공통 레이아웃 - Path alias, storybook path alias 세팅 

client/.eslintrc.json
eslint, prettier가 정상작동이 되지 않아
eslintrc.json에 
`"project": ["./tsconfig.json"],`
해당 코드를 추가하였습니다.
=> [FE] 코어 - 개발 환경 설정 - eslintrc 설정 추가

client/src/components/BottomNavigationBar/index.tsx
기존 컴포넌트에서 function으로 선언되던 것을
내부 컨벤션에 맞추어 화살표 함수로 변경하였습니다.
=> [FE] 코어 - 공통 레이아웃 - 하단 네비게이션바 코드 리팩토링

.github/workflows/deplol.yml
>  github action을 위한 .yml 파일 설정
> 서버 환경에서의 자동 배포를 위한 스크립트 작성
```
cd /root/Web04-Fitory
git pull origin main
cd /root/Web04-Fitory/server
npm install package.json
rm -rf dist
npm run build
cd /root/Web04-Fitory/client
npm install package.json
rm -rf dist
npm run build
pm2 reload all
```
=> [BE] 코어 - 개발 환경 설정 - Github Action 자동 배포 설정

.gitignore, server/.eslintrc.json, server/tsconfig.json
> nestjs에 적합하게 gitignore, eslint tsconfig 설정 수정
=> [BE] 코어 - 개발 환경 서정 - nestjs에 적합하게 gitignore, eslint tsconfig 설정 수정

client/src/components/BottomNavigationBar/style.ts
하단 네비게이션바의 포지션을 하단으로 조정했습니다.
```
position: fixed;
bottom: 0;
left: 0;
```
=> [FE] 코어 - 공통 레이아웃 - 하단 네비게이션바

server/.eslintrc.json, server/package-lock.json, server/package.json
> nestjs에 적합하지 않는 eslint 설정 수정
=> [BE] 코어 - 개발 환경 설정 - eslint, package.json

server/src/exception/HttpError.ts, server/src/exception/HttpExceptionFilter.ts, server/src/user/dto/create-user.dto.ts, server/src/user/dto/user-login.dto.ts, server/src/user/user.controller.spec.ts, server/src/user/user.controller.ts, server/src/user/user.module.ts, server/src/user/user.service.spec.ts, server/src/user/user.service.ts
> 로그인 유저 정보를 DB에 등록
> 유저 정보를 get
> http 에러 처리
=> [BE] API 구현 - USER API - 데모를 위한 기초 구현

server/package-lock.json, server/package.json, server/src/main.ts
> swagger 설치 후 세팅하여 API가 잘 뜨는지 확인함
=> [BE] API 구현 - 세팅 - swagger 세팅

server/src/exercises/dto/every-date.dto.ts, server/src/exercises/dto/history-of-month.dto.ts, server/src/exercises/exercises.controller.ts, server/src/exercises/exercises.service.ts
> 단일 사용자가 운동한 날짜를 배열로 반환하는 API 구현
> 사용자 id와 월을 요청하면 해당 사용자가 해당 월에 수행했던 운동 기록들을 응답하는 API
=> [BE] API 구현 - EXERCISE API - Every Exercise History API, Month Exercise History API 구현

server/src/sbd_records/dto/best-record.dto.ts, server/src/sbd_records/dto/every-record.dto.ts, server/src/sbd_records/sbd_records.controller.ts, server/src/sbd_records/sbd_records.service.ts
> 사용자의 Id를 요청하면 해당 사용자가 지금껏 기록한 SBD 기록들을 응답하는 API 구현
> 사용자 Id를 요청하면 해당 사용자의 SBD 측정 최고기록을 응답하는 API 구현
> 개발할 때 참고한 자료를 첨부할 경우 여기에 추가하세요.
=> [BE] API 구현 - Record API - Best & Every SBD Record API 구현

server/src/users/entities/user.entity.ts, server/src/users/users.controller.ts, server/src/users/users.service.ts
=> [BE] API 구현 - Search API 구현 (공통) - Every User Name API 구현

server/src/routines/dto/routine-list.dto.ts, server/src/routines/entities/routine.entity.ts, server/src/routines/routines.controller.ts, server/src/routines/routines.service.ts, server/src/users/entities/user.entity.ts
> 사용자의 Id를 요청하면 해당 사용자의 루틴 목록(uuid, 루틴 이름)을 응답하는 API
=> [BE] API 구현 - Routine API (공통) - Routine List API 구현

server/src/users/entities/user.entity.ts, server/src/users/users.controller.ts, server/src/users/users.service.ts
- 쿼리문을 이용해 user id를 넘기면 서버 DB에 해당 user id의 user data들을 갖고온다.
- 예) http://localhost:8080/users/get?id=1
- 스웨거 적용을 위해 `@ApiOperation` 및 `@ApiQuery` 작성
=> [BE] API 구현 - USER API (공통) - Get User Data API 구현

client/src/components/Calendar/CalendarBody.tsx, client/src/components/Calendar/CalendarElement.tsx, client/src/components/Calendar/CalendarHeader.tsx, client/src/components/Calendar/style.ts, client/src/pages/HomePage/index.tsx
#76 
기존 남겨져있던 any타입을 전부 올바른 타입으로 맞게 변경하였습니다.
배포환경에서 올바르게 출력되도록 스타일을 재지정했습니다.
- width 재설정
- 폰트 EXTRA_SMALL로 변경
=> [FE] 코어 - 공통 레이아웃 - 달력 (타입 설정 및 스타일 변경)

client/src/components/Calendar/CalendarElement.tsx, client/src/constants/enums.ts
#76 
기존 string타입을 DayTypes로 변경 하면서 글자색이 적용되지 않는 현상이 발생했습니다.
빠르게 수정하였습니다.
=> [FE] 코어 - 공통 레이아웃 - 달력 (색상 재지정)

server/src/exercises/exercises.service.ts
사용자가 100kg 운동을 5회 성공했을때 500kg가 아니라 100kg로 누적되는 로직 이슈가 있어서 이를 수정
=> [BE] API 구현 - Exercise API - getTotalVolume 구하는 로직 수정

server/src/oauth/google-oauth/dto/google-user.dto.ts, server/src/oauth/google-oauth/google-oauth.controller.ts, server/src/users/users.service.ts
> google oauth dto에 타입 및 스웨거용 설명 추가
=> [BE] API 구현 - OAuth API - DTO 설정 추가

server/src/alarms/alarms.controller.ts, server/src/exception/exceptions.ts, server/src/exercises/exercises.controller.ts, server/src/exercises/exercises.service.ts, server/src/routines/routines.controller.ts, server/src/sbd_records/sbd_records.controller.ts, server/src/users/users.controller.ts, server/src/validation/validation.ts
클라이언트에서 GET 요청으로 데이터를 보낼때 오는 데이터의 검증의 필요성을 느낌
> userId에 문자 또는 bad 쿼리를 넣을 수 있기 때문에 이를 방어하기 위함
POST 요청으로 오는 데이터는 DTO로 검증하도록 하고,
userId만 가지고 요청하는 GET 요청은 간단하게 예외처리로 처리하기 위해 다음과 같이 구현함
❗❗ 위 검증 절차는 모두 Controller에서 하도록 함
> Service까지 가기 전에 빠르게 처리하고 응답하기 위함
> 또한 잘못된 요청이 DB에 접근하는 것을 막기 위함 (SQL Injection 방어)
validation 폴더 안에 `validation.ts` 파일을 만들어 정규식으로 값이 유효한지 true, false로 반환
Exception 클래스 안에 메서드들을 선언하여 예외 처리
userId에 0을 넣으면 아래와 같이 응답이 옴
> 개발할 때 참고한 자료를 첨부할 경우 여기에 추가하세요.
=> [BE] API 구현 - 세팅 - API 요청 데이터 검증 절차 구현 (1차)

server/src/domain/exercises/converter/exercise.converter.ts, server/src/main.ts
=> [BE] API 구현 - Get Every Exercise Date API 날짜 중복 제거

server/src/domain/routines/routines.controller.ts, server/src/domain/users/users.controller.ts, server/src/domain/users/users.service.ts
> 원본 PR https://github.com/boostcampwm-2022/Web04-Fitory/pull/167
Controller 내 불필요한 async 가 존재
=> ♻️ [refactor] : Controller 내 불필요한 async 키워드 제거

client/app.config.json
=> 서버 배포 1차 - app.config.json

client/src/pages/SearchPage/index.tsx, server/src/main.ts
=> 서버 배포 1차 - cors 에러 수정

server/src/main.ts
=> 서버 배포 1차 - cors 수정

server/src/config/typeorm.config.ts, server/src/domain/alarms/entities/alram.entity.ts, server/src/domain/mock/mock.controller.ts, server/src/domain/mock/mock.service.ts, server/src/domain/sbd_records/entities/sbd_record.entity.ts, server/src/utils/initDB.ts
1970년부터 누적된 초로 저장 & 응답하는 방식에 문제가 있어
이를 timestamp 타입으로 교체하였음
=> [BE] Timestamp 타입 변경

client/src/pages/SearchPage/index.tsx, client/src/pages/SearchPage/styles.ts
#206 
기존 검색페이지에서 추천 친구 카드 스크롤러 레이아웃을 적용
추천친구 api는 아직 연동이 되지 않았음
https://user-images.githubusercontent.com/78866590/204266595-73ff73aa-0fce-465c-8ac5-c89775034a07.mov
=> [FE] 검색 페이지 - 검색페이지 - UI 구현

server/src/domain/users/users.controller.ts, server/src/domain/users/users.service.ts, server/src/exception/exceptions.ts
- DB에서 유저 이름 중복 검사 후, 중복이 없으면 true, 중복이면 false 반환
=> [BE] API 구현 - USER API - user name 중복 검사

server/src/domain/users/users.controller.ts, server/src/domain/users/users.service.ts
- 유저 ID를 get query로 보내 해당 유저의 나이 +-1와 몸무게 +-5의 사용자들중 무작위로 5개를 추출해 response한다.
**반환 형식** 
```
{
{
"ok": true,
"statusCode": 200,
"response": {
"recommendWeight": [
{
"user_name": "홍율기",
"profile_image": "http://default.image"
},
{
"user_name": "여라이",
"profile_image": "http://default.image"
},
{
"user_name": "심유일",
"profile_image": "http://default.image"
},
{
"user_name": "형은유",
"profile_image": "http://default.image"
},
{
"user_name": "선기훈",
"profile_image": "http://default.image"
}
],
"recommendAge": [
{
"user_name": "부송우",
"profile_image": "http://default.image"
},
{
"user_name": "곽나겸",
"profile_image": "http://default.image"
},
{
"user_name": "한우원",
"profile_image": "http://default.image"
},
{
"user_name": "반정준",
"profile_image": "http://default.image"
},
{
"user_name": "이종원", …
```
=> [BE] API 구현 - RECOMMAND API - 유저 친구 추천

server/src/domain/alarms/alarms.controller.ts, server/src/domain/alarms/alarms.module.ts, server/src/domain/alarms/alarms.service.ts
#217 
특정 사용자가 받은 알람들의 정로 (보낸 이의 이름, 보낸 이의 프로필 사진 등)을 응답하는 API
=> [BE] API 구현 - Alarm - Get Alarm List

server/src/domain/follows/follows.controller.ts, server/src/domain/follows/follows.module.ts, server/src/domain/follows/follows.service.ts
#225 #226 
팔로잉 / 팔로워 사용자의 프로필을 랜더링하는 데 필요한 정보들을 응답한다.
=> [BE] API 구현 - Follow - Get Following / Follower List API 구현

server/src/domain/exercises/dto/exercise.dto.ts, server/src/domain/exercises/exercises.controller.ts, server/src/domain/exercises/exercises.module.ts, server/src/domain/exercises/exercises.service.ts, server/src/domain/users/users.service.ts, server/src/exception/exceptions.ts
#238 
사용자가 운동 기록완료를 누르면 해당 운동기록을 검증 후 저장하는 API
=> [BE] API 구현 - Exercise - Save Exercise API 구현

server/src/domain/oauth/google-oauth/google-oauth.controller.ts, server/src/domain/oauth/google-oauth/google-oauth.module.ts, server/src/domain/users/users.controller.ts
- access token 쿠키 기한 10년으로 수정
- 리팩토링
=> [BE] API 구현 - AUTH API - 쿠키 기한 수정, 리팩토링

server/src/domain/alarms/alarms.controller.ts, server/src/domain/alarms/alarms.module.ts, server/src/domain/alarms/alarms.service.ts, server/src/domain/exercises/exercises.controller.ts, server/src/domain/exercises/exercises.module.ts, server/src/domain/follows/follows.controller.ts, server/src/domain/follows/follows.module.ts, server/src/domain/routines/routines.controller.ts, server/src/domain/routines/routines.module.ts, server/src/domain/sbd_records/sbd_records.controller.ts, server/src/domain/sbd_records/sbd_records.module.ts, server/src/domain/users/entities/user.entity.ts, server/src/domain/users/users.controller.ts, server/src/domain/users/users.service.ts
=> [BE] API - 존재하지 않는 userId 요청시 404 반환

server/src/config/typeorm.config.ts, server/src/domain/oauth/google-oauth/google-oauth.service.ts, server/src/domain/oauth/jwt/jwt.strategy.ts, server/src/domain/users/users.controller.ts, server/src/domain/users/users.service.ts, server/src/main.ts
=> [BE] API 구현 - 리팩토링

server/src/domain/exercises/dto/exercise.dto.ts, server/src/domain/follows/dto/follow.dto.ts, server/src/domain/follows/follows.controller.ts, server/src/domain/follows/follows.service.ts, server/src/exception/exceptions.ts
=> [BE] API - Follow - Do & Cancel Follow API 구현

client/src/api/ChallengeAPI.ts, client/src/api/ExerciseAPI.ts, client/src/api/UserAPI.ts, client/src/components/Calendar/CalendarBody.tsx, client/src/components/CalendarHeatMap/index.tsx, client/src/components/UserInfoSummary/index.tsx, client/src/components/UserInfoSummary/style.ts, client/src/constants/enums.ts, client/src/hooks/query/useAllExerciseDate.ts, client/src/hooks/query/useBestChallengeScore.ts, client/src/hooks/query/useExerciseProfile.ts, client/src/hooks/query/useUserInfo.ts, client/src/services/Exception.ts, client/src/services/HttpClient.ts, client/src/types/challenge.d.ts, client/src/types/exercise.d.ts, client/src/utils/convertWeightUnits.ts
- 사용자 정보 API 연동 및 적용
- 사 용자 최고 3대 챌린지 점수 API 연동 및 적용
- 사용자의 모든 운동 기록 날짜 API 연동 및 적용
> 홈 페이지에서 필요한 데이터를 서버 API를 통해 요청한다.
=> [FE] 홈 페이지 - API 연동

server/src/config/typeorm.config.ts, server/src/domain/alarms/alarms.module.ts, server/src/domain/alarms/alarms.service.ts, server/src/domain/exercises/exercises.controller.ts, server/src/domain/exercises/exercises.module.ts, server/src/domain/users/users.service.ts
#271 
특정 사용자가 운동을 완료하여 API를 쏘면
그 사람을 팔로우하는 사용자들에게 알림이 가도록
Alarm 테이블에 row 가 삽입됨
DB에 실제 반영됨을 테스트 후 확인함
=> [BE] API - Exercise - 운동 완료시 알람 발송 기능 구현

client/src/App.tsx, client/src/api/ChallengeAPI.ts, client/src/api/ExerciseAPI.ts, client/src/api/UserAPI.ts, client/src/pages/JoinPage/index.tsx, client/src/services/ClientStorage.ts, client/src/services/HttpClient.ts, client/src/types/challenge.d.ts, client/src/types/user.d.ts
https://user-images.githubusercontent.com/78866590/205071189-2705775a-a7d2-4f8b-bc69-d5072b295a87.mov
22.12.01 22시 55분 기준, 모든 닉네임이 존재하는 현상
> uncaught error: a component suspended while responding to synchronous input. this will cause the ui to be replaced with a loading indicator. to fix, updates that suspend should be wrapped with starttransition.
> 프론트엔드에서 나타나는 버그를 해결한다.
=> [FE] 회원가입 닉네임 중복 여부 확인 API 버그 & React Query 비동기 처리 에러 해결

server/src/domain/oauth/google-oauth/google-oauth.controller.ts
=> 서버 배포 2차 - cookie secure 설정 변경

client/package-lock.json, client/src/App.tsx, client/src/constants/enums.ts, client/src/pages/FollowPage/index.tsx, client/src/pages/FollowPage/style.ts, client/src/pages/ProfilePage/index.tsx, client/src/pages/SearchPage/index.tsx, client/src/pages/SearchPage/styles.ts, client/src/pages/SearchPage/utils.tsx, client/src/types/user.d.ts, client/src/utils/SearchUtils.ts, client/src/utils/drawSearchedUserList.tsx
- user list가 안받아와지는 문제 해결 PR 적용
=> 서버 배포 2차 - #289 PR 적용

server/src/domain/follows/entities/follow.entity.ts, server/src/domain/routines/entities/routine.entity.ts, server/src/domain/sbd_records/sbd_records.service.ts, server/src/domain/users/users.service.ts
클라이언트 시간이 아니라 서버 시간 기준 timestamp를 찍기 위해 설정
=> [BE] API - Record - 현재 timestamp 응답하도록 설정

server/src/domain/alarms/alarms.controller.ts, server/src/domain/exercises/dto/exercise.dto.ts, server/src/domain/exercises/exercises.controller.ts, server/src/domain/follows/follows.controller.ts, server/src/domain/routines/routines.controller.ts, server/src/domain/sbd_records/sbd_records.controller.ts, server/src/domain/users/users.controller.ts
굳이 userId를 검증하지 않아도 되는 부분에 대해 제거함
Do Follow, Cancel Follow는 악용의 여지가 있기 때문에 남겨둠
=> [BE} API - 대응 - 존재하지 않는 사용자 ID 요청 검증 취소

server/src/domain/alarms/alarms.service.ts, server/src/domain/users/users.controller.ts, server/src/domain/users/users.service.ts, server/src/middleware/valid-user/valid-user.middleware.ts
Recommad API 에 user_id 추가 및 user_name -> name으로 이름 수정
=> [BE] API - Recommend - 응답 양식 수정

client/src/components/SearchResultUserProfile/style.ts, client/src/components/SearchedUserList/index.tsx, client/src/components/SearchedUserList/style.ts, client/src/pages/FollowPage/index.tsx, client/src/pages/FollowPage/style.ts, client/src/pages/SearchPage/index.tsx, client/src/pages/SearchPage/styles.ts, client/src/pages/SearchPage/utils.tsx
#296 
저번 피드백을 기반으로 작업사항을 만들고 반영하였습니다.
https://zxchsr.tistory.com/301
=> [FE] 검색페이지 - 검색바 - 스타일링/ drawSearchedUserList 위치 변경 

client/src/api/ChallengeAPI.ts, client/src/api/ExerciseAPI.ts, client/src/api/UserAPI.ts, client/src/components/RoutineScroller/index.tsx, client/src/components/RoutineScroller/style.ts, client/src/hooks/query/useDeleteRoutine.ts, client/src/pages/RecordPage/index.tsx, client/src/services/HttpClient.ts, client/src/stores/exerciseStore.ts, client/src/types/exercise.d.ts
루틴 수정을 어떻게 수행하도록 UI를 구현할지 고민입니다..
- 그래서 루틴 수정은 일단 미루고 다른 작업을 우선으로 하겠습니다.
- 세트 증가 시 이전 세트와 같은 값을 가지도록 구현
- 루틴 저장 예외 처리 구현
- 루틴 삭제 기능 구현
> 운동 기록 페이지으 루틴 저장, 삭제 등 API를 연동 및 적용한다.
=> [FE] 운동 기록 페이지 - 루틴 관련 API 연동

client/package-lock.json, client/package.json, client/src/hooks/query/useBestChallengeScore.ts, client/src/hooks/query/useExerciseProfile.ts, client/src/hooks/query/useRecentChallengeTime.ts, client/src/hooks/query/useRoutineList.ts, client/src/hooks/query/useUserInfo.ts, client/src/stores/exerciseStore.ts, client/src/utils/updateOneElementFromArray.ts
> [Immer.js 도입기](https://github.com/boostcampwm-2022/Web04-Fitory/wiki/Immer.js-%EB%8F%84%EC%9E%85%EA%B8%B0)
-  Zushand Store에 Immer.js를 적용하여 불변성 보장
-  React Query의 `useQuery` 반환 데이터에 read only 적용
> React Qeury 커스텀 Hook 반환 객체의 불변성 보장과 복잡한 데이터 구조의 상태 불변성 관리를 위한 Immer.js 도입
=> [FE] 코어 - 불변성 관리

server/src/app.module.ts, server/src/domain/users/users.controller.ts, server/src/main.ts
=> 서버 배포 3차 - 오류 수정

server/src/middleware/zero-downtime-deploy/graceful-shutdown.ts, server/src/middleware/zero-downtime-deploy/is-disable-keep-alive.global.ts, server/src/middleware/zero-downtime-deploy/set-response-header.middleware.ts
=> 서버 배포 3차 : 무중단 배포 설정

server/package-lock.json, server/package.json, server/src/domain/follows/follows.service.ts
SOFT Delete 고려하지 않은 쿼리를 수정함
팔로우 취소 동작시 soft delete가 일어나는데
정작 마이페이지에서 팔로우 카운트를 가져오는 쿼리는
soft delete를 고려하지 않은 쿼리가 있었고, 이를 수정함
=> [BE] API - Follow - 팔로우 취소 오류 수정

server/src/domain/alarms/alarms.controller.ts
=> 서버 배포 3차 : alarm sse CORS 수정

client/public/index.html
=> 서버 배포 3차 - index.html 삭제

server/src/domain/mock/mock.service.ts, server/src/guard/jwt.guard.ts, server/src/main.ts
=> 서버 배포 3차 - allowedHeaders user_id 추가

server/src/main.ts
=> 서버 배포 3차 - allowedHeaders user_id 추가

client/.eslintrc.json, client/public/index.html, client/src/components/MyPageEditButton/style.ts, client/src/components/MyPageUserProfile/index.tsx, client/src/components/MyPageUserProfile/style.ts, client/src/pages/ProfilePage/index.tsx, client/src/pages/ProfilePage/style.ts, server/src/domain/mock/mock.controller.ts
- 잔디 추가
- 루틴 리스트 추가
> 마이 페이지 하단에 잔디와 루틴 리스트를 렌더링한다.
=> [FE] 마이 페이지 - 하단

client/src/api/ExerciseAPI.ts, client/src/components/TierGraph/index.tsx, client/src/components/TierGraph/plugin.ts, client/src/components/TierGraph/style.ts, client/src/pages/ProfilePage/index.tsx, client/src/types/exercise.d.ts
#400 
#257 
#316 
> 이곳에 요약 내용을 쓰세요.
4번 유저의 그래프
[날짜변환](https://askforyou.tistory.com/60)
=> [FE] 통계페이지 - 차트 - api 연동

client/.eslintrc.json, client/src/api/ExerciseAPI.ts, client/src/components/MyPageEditButton/style.ts, client/src/components/MyPageUserProfile/index.tsx, client/src/components/MyPageUserProfile/style.ts, client/src/components/TierGraph/index.tsx, client/src/components/TierGraph/plugin.ts, client/src/components/TierGraph/style.ts, client/src/pages/ProfilePage/index.tsx, client/src/pages/ProfilePage/style.ts, client/src/types/exercise.d.ts, server/k6Test.js, server/src/domain/mock/mock.controller.ts, server/src/domain/mock/mock.service.ts
=> 서버 배포 3차 - feature PR 머지

client/src/pages/ProfilePage/index.tsx
=> 서버 배포 3차 - profile page import 추가

client/src/api/UserAPI.ts, client/src/pages/FollowPage/index.tsx, client/src/pages/ProfilePage/index.tsx
- 팔로우, 팔로잉 API 호출시 헤더에 user_id 넣기
=> 서버 배포 3차 - 팔로우, 팔로잉 API 호출 수정

server/src/domain/users/users.controller.ts
- update user시 500에러 나는 버그 수정
- 프로필 이미지를 바꾸지 않을 경우 filePath가 없는데 upload를 실행해서 발생하는 버그 수정
=> [BE] API 구현 - USER API - update user 버그 수정

server/src/config/typeorm.config.ts, server/src/domain/alarms/alarms.controller.ts, server/src/domain/exercises/exercises.service.ts, server/src/domain/oauth/google-oauth/google-oauth.module.ts, server/src/domain/oauth/google-oauth/google-oauth.service.ts, server/src/guard/jwt.strategy.ts, server/src/main.ts, server/test/app.e2e-spec.ts, server/test/jest-e2e.json, server/tsconfig.json
env에서 path에서 발생으로 인해 이를 e2e.json에 정의함
=> [BE] test - setting - alias path 수정

server/src/utils/classify.ts
브론즈가 1부터 시작하기 때문에 index를 +1 하여 수정함
=> [BE] 티어 인덱스 버그 수정

server/src/domain/users/options/multer_options.ts, server/src/domain/users/users.service.ts
프론트에서 이미지 불러와지지 않는 문제로 인해 경로 수정
=> [BE] DB - multer - user_profiles 로 경로 수정

server/src/domain/users/users.controller.ts
=> [BE] DB - multer - 파일 없는 요청 왔을때 예외처리

server/test/record.e2e-spec.ts
- Record API Jest Test Code 작성
=> [BE] 테스팅 - RECORD API - Jest Test Code 작성

client/src/api/UserAPI.ts, client/src/components/MyPageEditButton/index.tsx, client/src/components/MyPageUserProfile/index.tsx, client/src/components/ProfileImageContainer/index.tsx, client/src/pages/FollowPage/index.tsx, client/src/pages/ProfileEditPage/index.tsx, client/src/pages/ProfilePage/index.tsx, client/src/pages/SearchPage/index.tsx, client/src/types/user.d.ts
#443 
마이페이지 프로필 사진 업로드를 구현했습니다.
린트에러를 수정하였습니다.
https://user-images.githubusercontent.com/78866590/207073679-3f96aba0-2ab0-4fda-990a-bea7842e303c.mov
=> [FE] 마이페이지 - 마이페이지 수정 - 프로필 사진 업로드

client/src/components/ProfileImageContainer/style.ts, client/src/components/RecommendUserCard/style.ts, client/src/components/TierGraph/option.ts, client/src/pages/SearchPage/index.tsx
#454 
pr 피드백 기반 스타일링 수정완료
차트 버그 수정 완료
=> [FE] 차트버그 / 스타일링 개선

server/test/users.e2e-spec.ts
=> [BE] 테스팅 - USER API - 버그 수정

server/test/record.e2e-spec.ts
=> [BE] 테스팅 - RECORD API - 자동 종료 수정

server/src/domain/alarms/alarms.controller.ts, server/src/domain/alarms/alarms.service.ts, server/src/domain/users/users.controller.ts, server/test/exercise.e2e-spec.ts, server/test/users.e2e-spec.ts
Exercise API에 대한 테스트
GET 요청은 단순 검사만 하고
이제 POST 요청에 대해 시나리오 e2e 테스트를 진행함
운동 완료시, 팔로워들에게 알림이 정말 가서 DB에 반영이 되는지,
운동 완료시, 예전 팔로워에게 (지금은 팔로우 취소된 상태) 알림이 정말 가지 않는 게 맞는지
확인하는 테스트 코드 작성
=> [BE] test - exercise 테스트 코드 파일 생성

client/src/components/SearchResultUserProfile/style.ts, client/src/components/SearchedUserList/style.ts, client/src/hooks/query/follow/useFollowUserList.ts
=> [FE] 팔로우 페이지 - 팔로우 리스트 캐싱 버그 해결

client/src/components/FollowButton/style.ts, client/src/components/RecommendUserCard/style.ts
=> [FE] - 검색 페이지 - 추천 사용자 리스트 hover 추가

server/src/domain/follows/follows.controller.ts, server/src/domain/users/users.service.ts
자기 자신을 추천 사용자로 제공하는 것을 막음
자기 자신을 팔로우 하는 것을 막음
간단하게 조건문 달아서 로직 구현함
=> [BE] API - 자기 자신 추천 막기, 자기 자신 팔로우 막기 

server/src/main.ts, server/src/utils/env.ts
=> 서버 배포 4차 - eslint 수정

.github/workflows/deplol.yml, server/src/main.ts
=> 서버 배포 4차 - 가드 설정

server/src/domain/users/users.service.ts, server/src/main.ts, server/src/middleware/zero-downtime-deploy/graceful-shutdown.ts, server/src/middleware/zero-downtime-deploy/is-disable-keep-alive.global.ts, server/src/middleware/zero-downtime-deploy/set-response-header.middleware.ts
=> 서버 배포 4차 - pm2 process 설정

server/src/utils/env.ts
=> 서버 배포 4차 - env 경로 수정

client/package-lock.json, client/package.json, client/public/index.html, client/webpack.config.js
> manifest와 service worker가 등록되지 않은 문제 해결
=> [FE] 코어 - PWA - manifest와 service worker가 등록되지 않은 문제 해결

client/src/utils/SearchUtils.ts
=> [FE] 검색페이지 - 검색 -  검색어 입력 안할시 검색요청 안하게 처리

client/src/components/SearchedUserList/index.tsx, server/src/domain/users/users.service.ts
=> 서버 배포 4차 - query select 수정

server/src/domain/users/users.service.ts
=> 서버 배포 4차 - 파일 경로 수정

client/public/index.html, client/public/manifest.json, client/src/components/AppInstallPrompt/index.tsx, client/src/components/AppInstallPrompt/style.ts, client/src/components/BottomNavigationBar/style.ts, client/src/components/MainContainer/style.ts, client/src/components/TopNavigationBar/style.ts, client/src/pages/HomePage/style.ts, client/src/styles/Theme.ts, client/src/utils/getPWADisplayMode.ts
- 앱이 설치되어있으면 앱 설치 모달 띄우지 않기
- 하단 네비게이션바 padding-bottom 늘리기
- 홈 화면에 설치되는 앱 로고 여백 제거
> PWA 배포 후 나타나는 문제들을 해결한다.
=> FE] 코어 - PWA - 배포 후 나타나는 문제 해결

client/public/index.html
- PWA에서 input 클릭시 확대되는 현상을 meta 태그 수정으로 해결
>  PWA에서 input 클릭시 확대되는 현상을 해결한다.
=> [FE] 코어 - PWA - input 클릭시 확대되는 현상 해결

client/public/index.html, client/public/manifest.json, client/src/components/AppInstallPrompt/index.tsx, client/src/components/AppInstallPrompt/style.ts, client/src/components/BottomNavigationBar/style.ts, client/src/components/MainContainer/style.ts, client/src/components/TopNavigationBar/style.ts, client/src/pages/HomePage/style.ts, client/src/styles/Theme.ts, client/src/utils/getPWADisplayMode.ts
=> 서버 배포 4차 - PWA 수정

server/k6/cpu-test.js, server/src/domain/sbd_statistics/sbd_statistics.service.ts
=> [BE] API 구현 - STATISTICS API - 통계 데이터 API 최적화

server/test/routine.e2e-spec.ts
=> [BE] Test - Routine 테스트 코드 작성 

server/test/record.e2e-spec.ts, server/test/users.e2e-spec.ts
=> [BE] API - test - User Recommend API 테스트 코드 작성

server/src/domain/alarms/alarms.controller.ts, server/src/domain/alarms/alarms.service.ts, server/src/domain/follows/follows.service.ts, server/src/domain/oauth/google-oauth/google-oauth.controller.ts, server/src/domain/users/entities/user.entity.ts, server/src/domain/users/users.service.ts, server/src/main.ts
user 테이블에 follow 관련 컬럼 추가
user 테이블에 follow 관련 컬럼 추가
=> [BE] DB - user 테이블에 follow 관련 컬럼 추가

server/src/domain/sbd_statistics/entities/sbd_statistics.entity.ts
=> [BE] DB - multi index 설정

server/src/domain/sbd_records/sbd_records.module.ts, server/src/domain/sbd_records/sbd_records.service.ts, server/src/domain/users/users.service.ts
- 3대 챌린지 등록 시 통계에 반영 안되던 버그 수정
```
{
"ok": true,
"statusCode": 200,
"response": {
"message": "Record Submit Success",
"tier": 2
}
}
```
=> [BE] API 구현 - RECORD API - 통계에 반영 안되던 버그 수정

client/src/components/TierGraph/index.tsx, client/src/components/TierGraph/plugin.ts, client/src/components/TierGraph/style.ts
차트에서 체중 변경시 색이 다르게 출력되던 현상을 해결하고
티어 그래프를 보여줄 때, 기준을 보여주어 명확하게 하였습니다.
차트를 그리는 기준은 '현재 체중' 기준입니다.
> 개발할 때 참고한 자료를 첨부할 경우 여기에 추가하세요.
=> FE- 차트 개선작업.

server/src/domain/users/users.service.ts, server/src/main.ts
=> 서버 배포 4차 - 로고 이슈 해결

server/src/domain/users/entities/user.entity.ts, server/src/domain/users/users.service.ts
언젠가부터 image가 profile.image로 저장이 되어
이를 default.image로 변경
=> [BE] DB - entity 이름 수정

server/src/main.ts
=> 서버 배포 - main.ts 수정

server/src/domain/sbd_statistics/sbd_statistics.service.ts
=> 서버 배포 - 통계 데이터 API typeorm 수정

server/k6/cpu-test.js, server/src/domain/sbd_records/sbd_records.controller.ts
=> 서버 배포 - 3대 챌린지 예외 처리
